### PR TITLE
Fix issues with auto_init destroying repositories

### LINKED ISSUE #155: Changing `auto` init value should not force a repo to be destroy/created
### Terraform Version

```
$ terraform --version
Terraform v0.11.7

Your version of Terraform is out of date! The latest version
is 0.11.8. You can update by downloading from www.terraform.io/downloads.html
```
Plugin version `1.3`

### Affected Resource(s)
Please list the resources as a list, for example:
- github_repository

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
resource "github_repository" "example" {
  name        = "example"
  description = "My awesome codebase"
  auto_init = false

  private = true
}
```

```hcl
resource "github_repository" "example" {
  name        = "example"
  description = "My awesome codebase"
  auto_init = true

  private = true
}
```

### Expected Behavior

`auto_init: (Optional) Meaningful only during create; set to true to produce an initial commit in the repository.`

To me this should mean that changes to this should ignore any changes. I found in my org that it was something that we used to also toggle branch protection count.

It should ideally note that there was a change but not actually send that request as it does not make sense that someone accidentally or intentionally flipping the value would blow up their code base.

### Actual Behavior
marks the resource for deletion/creation

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan`
1. `terraform apply`
1. make changes to flip `auto_init` value
1. `terraform plan`

### References

- https://github.com/sous-chefs/terraform-github-org/pull/111
- https://github.com/terraform-providers/terraform-provider-github/issues/148
- https://github.com/terraform-providers/terraform-provider-github/pull/135

### PR DESCRIPTION
**Pull request by majormoses**
From github API perspective setting or modifying `auto_init` only makes sense in the context of creating a new repository. Changing it after is ignored by the github API which is the behavior we should (and use to) match. The only scenario where this makes sense to assume that changing this intends on a destructive action (blowing up a github repo is not something that should be easy accidentally) is when you use the `terraform taint` command but for very different reasons. This change is related to several PRs and issues that subverts the communities expectations with no real or perceived value.

For further context please see #155 #154 https://github.com/sous-chefs/terraform-github-org/pull/111 #135 

fixes #155 

Signed-off-by: Ben Abrams <me@benabrams.it>

### CODE REVIEW

**Comment by yordis** [comment]
@majormoses would you mind resolving the merge conflicts?

**Comment by majormoses** [comment]
> @majormoses would you mind resolving the merge conflicts?

Sure, I have not bothered keeping it up to date since it was not getting any love from maintainers.

**Comment by majormoses** [comment]
I think I got the tests working again but it looks like there are some unrelated errors: https://travis-ci.org/github/terraform-providers/terraform-provider-github/jobs/678001033#L497

File: github/resource_github_repository.go [hunk 1]
```diff
@@ -87,7 +87,7 @@ func resourceGithubRepository() *schema.Resource {
 			"auto_init": {
 				Type:     schema.TypeBool,
 				Optional: true,
-				ForceNew: true,
+				ForceNew: false,
```
Comment (anGie44) [inline github/resource_github_repository.go:90]: hi @majormoses! you can remove this `ForceNew` attribute all together since my default it's not set in a resource

Comment (majormoses) [inline github/resource_github_repository.go:90]:
```suggestion
```

Comment (majormoses) [reply github/resource_github_repository.go]: Makes sense 👍

**Comment by jcudit** [comment]
Thanks again for fixing this one @majormoses.  Glad this annoyance has been removed.

**Comment by majormoses** [comment]
Happy to help, looking forward to ripping some hacks out of our modules :grinning:
