### PR TITLE
 data_source/github_repositories: add sort capabilities 

### LINKED ISSUE #206: There is no option to sort repositories in github_repositories data source
Hi there,

### Terraform Version
Terraform v0.11.11

### Affected Resource(s)

- data.github_repositories

### Terraform Configuration Files
```hcl
data "github_repositories" "example" {
  query = "org:hashicorp language:Go"
}
```
### Expected Behavior
I expect the list to be sorted consistently, for example if I add another repository to the organisation.

### Actual Behavior

Possibly the new repos get added to the beginning of the list of repositories.

### Steps to Reproduce

1. `terraform apply`
2. Add a new repository
3. `terraform apply`

### Important Factoids

In the underlying library there are sort options: https://github.com/google/go-github/blob/master/github/search.go#L40
They are not used in the provider: https://github.com/terraform-providers/terraform-provider-github/blob/master/github/data_source_github_repositories.go#L60

### PR DESCRIPTION
**Pull request by tracypholmes**
Fixes #206 and added ability to sort

### CODE REVIEW

File: github/data_source_github_repositories.go [hunk 1]
```diff
@@ -2,6 +2,7 @@ package github
 
 import (
 	"context"
+	"github.com/hashicorp/terraform/helper/validation"
```
Comment (katbyte) [inline github/data_source_github_repositories.go]: I would run goimports on this file (sorts the imports)

File: website/docs/d/repositories.html.markdown [hunk 2]
```diff
@@ -27,6 +27,8 @@ The following arguments are supported:
 
 * `query` - (Required) Search query. See [documentation for the search syntax](https://help.github.com/articles/understanding-the-search-syntax/).
 
+* `sort` - (Optional) Sorts query. Valid values include `stars`, `fork`, and `updated`. Defaults to `updated`.
```
Comment (katbyte) [inline website/docs/d/repositories.html.markdown]: Would this sound better as: 
```suggestion
* `sort` - (Optional) Sorts the repositories returned by the specified attribute. Valid values include `stars`, `fork`, and `updated`. Defaults to `updated`.
```

File: github/data_source_github_repositories.go [hunk 3]
```diff
@@ -39,9 +46,15 @@ func dataSourceGithubRepositoriesRead(d *schema.ResourceData, meta interface{})
 	client := meta.(*Organization).client
 
 	query := d.Get("query").(string)
+	opt := &github.SearchOptions{
```
Comment (katbyte) [inline github/data_source_github_repositories.go]: Another option here would have been to pass the sort option into `searchGithubRepositories(client, query, sort)` keeping all the github specific search logic and types together while keeping this function a bit cleaner. WDYT?

File: github/data_source_github_repositories_test.go [hunk 4]
```diff
@@ -50,7 +76,16 @@ func TestAccGithubRepositoriesDataSource_noMatch(t *testing.T) {
...
+	query = %q
 }
 `, query)
 }
+
+func testAccCheckGithubRepositoriesDataSourceConfigWithSort(query, sort string) string {
+	return fmt.Sprintf(`
+data "github_repositories" "test" {
+	query = %q
+	sort = %q
```
Comment (katbyte) [inline github/data_source_github_repositories_test.go]:
```suggestion
	sort  = %q
```

File: github/data_source_github_repositories_test.go [hunk 5]
```diff
@@ -50,7 +76,16 @@ func TestAccGithubRepositoriesDataSource_noMatch(t *testing.T) {
 func testAccCheckGithubRepositoriesDataSourceConfig(query string) string {
 	return fmt.Sprintf(`
 data "github_repositories" "test" {
-	query = "%s"
+	query = %q
```
Comment (katbyte) [inline github/data_source_github_repositories_test.go]: Should we be removing the ""s from around string values? 🤔 While that may work in .12 some people may use the tests as an example and still be running .11. Would it be better to use the syntax that has the most compatibility until we officially retire .11?

Comment (katbyte) [reply github/data_source_github_repositories_test.go]: I just realized %q quoted 😅 It might make make more sense to leave this as "%s" to be explicit that there are quotes there.

File: website/docs/d/repositories.html.markdown (hunk 2 above)
Comment (tracypholmes) [reply website/docs/d/repositories.html.markdown]: Agreed. Was having a time with the wording on that.

File: github/data_source_github_repositories.go (hunk 3 above)
Comment (tracypholmes) [reply github/data_source_github_repositories.go]: That definitely makes sense. Did it this way because it was easier for me to read. I also felt like if someone needed to add additional parameters/values, they could just add it to the function.

File: github/data_source_github_repositories_test.go (hunk 5 above)
Comment (tracypholmes) [reply github/data_source_github_repositories_test.go]: I originally left it like that. But found over in AWS land, we are trying to be more consistent, so we use `%q` since that's what it does.
